const { keith } = require('../commandHandler');
//========================================================================================================================
//========================================================================================================================
//========================================================================================================================
//========================================================================================================================
//========================================================================================================================
//========================================================================================================================
//========================================================================================================================
//========================================================================================================================
//========================================================================================================================
//========================================================================================================================
//========================================================================================================================
//========================================================================================================================
//========================================================================================================================
//========================================================================================================================
keith({
    pattern: "thunder",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/thunder-text-effect-online-97.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "metalavatar",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/create-a-metal-avatar-by-your-name-299.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "underwater",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/3d-underwater-text-effect-online-682.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "firework",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/text-firework-effect-356.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "graffiticover",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/cover-graffiti-181.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "comic",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/create-online-3d-comic-style-text-effects-817.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "zodiac",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/free-zodiac-online-logo-maker-491.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "tattoo",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/make-tattoos-online-by-your-name-309.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "incandescent",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/text-effects-incandescent-bulbs-219.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "icetext",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/ice-text-effect-online-101.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================


keith({
    pattern: "hologram",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/free-create-a-3d-hologram-text-effect-441.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "greenneon",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/create-light-effects-green-neon-online-429.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "grafitti",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/cute-girl-painting-graffiti-text-effect-667.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "gradient",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/create-3d-gradient-text-effect-online-600.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "glowingtext",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/create-glowing-text-effects-online-706.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "glitch",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/create-digital-glitch-text-effects-online-767.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "galaxywallpaper",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/create-galaxy-wallpaper-mobile-online-528.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "galaxy",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/create-galaxy-style-free-name-logo-438.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "cloudeffect",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/write-text-effect-clouds-in-the-sky-online-619.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "dragonball",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/create-dragon-ball-style-text-effects-online-809.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "deletetext",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/create-eraser-deleting-text-effect-online-717.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "cartoonstyle",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/create-a-cartoon-style-graffiti-text-effect-online-668.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "advancedglow",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/advanced-glow-effects-74.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error(" logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "1917",
    desc: "Generate a logo with your text",
    category: "Logo",
    react: "💫",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create logo");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/1917-style-text-effect-523.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: ` logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error("logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});
//========================================================================================================================
keith({
    pattern: "blackpink",
    alias: ["bpink", "bp"],
    desc: "Generate a Blackpink-themed logo with your text",
    category: "Logo",
    react: "🎀",
    filename: __filename
}, async (context) => {
    try {
        const { client, m, fetchLogoUrl, text, args, quoted, botname, reply } = context;

        if (!args || !text) {
            return reply("_Please provide text to create the Blackpink logo._\n*Example:* `blackpink Jennie`");
        }

        const logoUrl = await fetchLogoUrl(
            "https://en.ephoto360.com/online-blackpink-style-logo-maker-effect-711.html",
            text
        );

        if (logoUrl) {
            await client.sendMessage(m.chat, {
                image: { url: logoUrl },
                caption: `🎀 Blackpink logo generated by ${botname}`
            }, { quoted });
        } else {
            reply("_Unable to fetch logo. Please try again later._");
        }

    } catch (error) {
        console.error("Blackpink logo command error:", error);
        context.reply(`❌ An error occurred:\n${error.message}`);
    }
});

